#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Davidschneiderinfo\PhpBoilerplate\Commands\SwitchDebugMode;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new SwitchDebugMode());

/** @noinspection PhpUnhandledExceptionInspection */
$application->run();

