services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - './logs/nginx:/var/log/nginx'
            - './docker/nginx/server.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            #- ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    composer:
        image: composer:2.8.6
        init: false
        volumes:
            - ".:/app"
        command: bash -c "git config --global --add safe.directory /app && composer install"
